-- Create schemas for all microservices
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS client;
CREATE SCHEMA IF NOT EXISTS exercise;
CREATE SCHEMA IF NOT EXISTS template;
CREATE SCHEMA IF NOT EXISTS workout;
CREATE SCHEMA IF NOT EXISTS schedule;
CREATE SCHEMA IF NOT EXISTS notification;

-- Grant privileges to application user
GRANT ALL PRIVILEGES ON SCHEMA auth TO coach;
GRANT ALL PRIVILEGES ON SCHEMA client TO coach;
GRANT ALL PRIVILEGES ON SCHEMA exercise TO coach;
GRANT ALL PRIVILEGES ON SCHEMA template TO coach;
GRANT ALL PRIVILEGES ON SCHEMA workout TO coach;
GRANT ALL PRIVILEGES ON SCHEMA schedule TO coach;
GRANT ALL PRIVILEGES ON SCHEMA notification TO coach;